### ISSUE TITLE
Fix spelling of `configuration_files/oh-my-zsh/installtion.zsh`

### ISSUE THREAD

**Issue by stegnerw** [I-question-this/configuration_files#1]
I was setting up zsh via oh-my-zsh on my personal system and wanted to see your setup as a reference.
Alas, I just couldn't figure out how you were installing your zsh config files, since there was no file named `installation.zsh`.
Right when I was about to give up, I noticed a glimmer of hope; there was a file named `installtion.zsh`, which is only a Levenshtein distance of 1 from `installation.zsh`!
Upon inspection of the file, I realized that it was, in fact, an installation file!
I highly recommend that this issue be fixed to avoid future confusion!

**Comment by king2b3** [comment]
I can give you a python program that generates Levenshtein distances of strings, so that the rest of this repository is useable.
